// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCAzeG1cyHIqAtgzDrL7IIw3eRBtOOQI',
    appId: '1:364659902498:web:9a307e2981c708ae1be27b',
    messagingSenderId: '364659902498',
    projectId: 'notesflutterfirebase',
    authDomain: 'notesflutterfirebase.firebaseapp.com',
    storageBucket: 'notesflutterfirebase.appspot.com',
    measurementId: 'G-46HKQYKNMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDyPKEyy81-cXWO4RWcgRW6PHBI8lYc8',
    appId: '1:364659902498:android:8c8c3b8471f090481be27b',
    messagingSenderId: '364659902498',
    projectId: 'notesflutterfirebase',
    storageBucket: 'notesflutterfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyz9lh5eT3xDTsj1NZUe0fx8aNqT7Rdlc',
    appId: '1:364659902498:ios:d2b5d2d42d6db84b1be27b',
    messagingSenderId: '364659902498',
    projectId: 'notesflutterfirebase',
    storageBucket: 'notesflutterfirebase.appspot.com',
    iosBundleId: 'com.example.belmondoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyz9lh5eT3xDTsj1NZUe0fx8aNqT7Rdlc',
    appId: '1:364659902498:ios:d173fbc4c120a1061be27b',
    messagingSenderId: '364659902498',
    projectId: 'notesflutterfirebase',
    storageBucket: 'notesflutterfirebase.appspot.com',
    iosBundleId: 'com.example.belmondoproject.RunnerTests',
  );
}
