// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23tG3MtvvVKGf3EUmvPlgDjNoB1V0njo',
    appId: '1:1066330038152:web:63873f6d9daa01271b643d',
    messagingSenderId: '1066330038152',
    projectId: 'databaseartproject',
    authDomain: 'databaseartproject.firebaseapp.com',
    databaseURL: 'https://databaseartproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseartproject.appspot.com',
    measurementId: 'G-8EFJHCMS8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnVXaN0IzcOdERKK1vOk6FVWmwwTDBmKM',
    appId: '1:1066330038152:android:90011e662c81f6db1b643d',
    messagingSenderId: '1066330038152',
    projectId: 'databaseartproject',
    databaseURL: 'https://databaseartproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseartproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEJAnZhCUIOGBbvizcjnegS1oe1OGH6Y',
    appId: '1:1066330038152:ios:a5ee9fdd0d0d5b571b643d',
    messagingSenderId: '1066330038152',
    projectId: 'databaseartproject',
    databaseURL: 'https://databaseartproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseartproject.appspot.com',
    iosBundleId: 'com.example.belmondoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEJAnZhCUIOGBbvizcjnegS1oe1OGH6Y',
    appId: '1:1066330038152:ios:a5ee9fdd0d0d5b571b643d',
    messagingSenderId: '1066330038152',
    projectId: 'databaseartproject',
    databaseURL: 'https://databaseartproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseartproject.appspot.com',
    iosBundleId: 'com.example.belmondoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB23tG3MtvvVKGf3EUmvPlgDjNoB1V0njo',
    appId: '1:1066330038152:web:00a6dd6865f206721b643d',
    messagingSenderId: '1066330038152',
    projectId: 'databaseartproject',
    authDomain: 'databaseartproject.firebaseapp.com',
    databaseURL: 'https://databaseartproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseartproject.appspot.com',
    measurementId: 'G-FL9Y8KP09L',
  );

}